
// This file has been generated by the GUI designer. Do not modify.
namespace movies
{
	public partial class Window
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Table table2;

		private global::Gtk.Button button13;

		private global::Gtk.Entry entrada;

		private global::Gtk.Button Estudios;

		private global::Gtk.HBox hbox1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textview1;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Button Actores;

		private global::Gtk.Button Directores;

		private global::Gtk.Button Productores;

		private global::Gtk.Button Peliculas;

		private global::Gtk.Button Search;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget movies.Window
			this.Name = "movies.Window";
			this.Title = global::Mono.Unix.Catalog.GetString("Window");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child movies.Window.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.button13 = new global::Gtk.Button();
			this.button13.CanFocus = true;
			this.button13.Name = "button13";
			this.button13.UseUnderline = true;
			this.button13.Label = global::Mono.Unix.Catalog.GetString("Apagar");
			this.table2.Add(this.button13);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2[this.button13]));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entrada = new global::Gtk.Entry();
			this.entrada.CanFocus = true;
			this.entrada.Name = "entrada";
			this.entrada.Text = global::Mono.Unix.Catalog.GetString("Search....");
			this.entrada.IsEditable = true;
			this.entrada.InvisibleChar = '●';
			this.table2.Add(this.entrada);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2[this.entrada]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.Estudios = new global::Gtk.Button();
			this.Estudios.CanFocus = true;
			this.Estudios.Name = "Estudios";
			this.Estudios.UseUnderline = true;
			this.Estudios.Label = global::Mono.Unix.Catalog.GetString("Estudios");
			this.table2.Add(this.Estudios);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2[this.Estudios]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView();
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.GtkScrolledWindow.Add(this.textview1);
			this.hbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
			w5.Position = 0;
			this.table2.Add(this.hbox1);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2[this.hbox1]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.Actores = new global::Gtk.Button();
			this.Actores.CanFocus = true;
			this.Actores.Name = "Actores";
			this.Actores.UseUnderline = true;
			this.Actores.Label = global::Mono.Unix.Catalog.GetString("Actores");
			this.hbox3.Add(this.Actores);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.Actores]));
			w7.Position = 0;
			w7.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.Directores = new global::Gtk.Button();
			this.Directores.CanFocus = true;
			this.Directores.Name = "Directores";
			this.Directores.UseUnderline = true;
			this.Directores.Label = global::Mono.Unix.Catalog.GetString("Directores");
			this.hbox3.Add(this.Directores);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.Directores]));
			w8.Position = 1;
			w8.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.Productores = new global::Gtk.Button();
			this.Productores.CanFocus = true;
			this.Productores.Name = "Productores";
			this.Productores.UseUnderline = true;
			this.Productores.Label = global::Mono.Unix.Catalog.GetString("Productores");
			this.hbox3.Add(this.Productores);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.Productores]));
			w9.Position = 2;
			w9.Fill = false;
			this.table2.Add(this.hbox3);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2[this.hbox3]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.Peliculas = new global::Gtk.Button();
			this.Peliculas.CanFocus = true;
			this.Peliculas.Name = "Peliculas";
			this.Peliculas.UseUnderline = true;
			this.Peliculas.Label = global::Mono.Unix.Catalog.GetString("Peliculas");
			this.table2.Add(this.Peliculas);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2[this.Peliculas]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.Search = new global::Gtk.Button();
			this.Search.CanFocus = true;
			this.Search.Name = "Search";
			this.Search.UseUnderline = true;
			this.Search.Label = global::Mono.Unix.Catalog.GetString("Search");
			this.table2.Add(this.Search);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2[this.Search]));
			w12.LeftAttach = ((uint)(2));
			w12.RightAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add(this.table2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.table2]));
			w13.Position = 0;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.Search.Clicked += new global::System.EventHandler(this.OnSearchClicked);
			this.Peliculas.Clicked += new global::System.EventHandler(this.OnPeliculasClicked);
			this.Actores.Clicked += new global::System.EventHandler(this.OnActoresClicked);
			this.Directores.Clicked += new global::System.EventHandler(this.OnDirectoresClicked);
			this.Productores.Clicked += new global::System.EventHandler(this.OnProductoresClicked);
			this.Estudios.Clicked += new global::System.EventHandler(this.OnEstudiosClicked);
			this.button13.Clicked += new global::System.EventHandler(this.OnButton13Clicked);
		}
	}
}
