
// This file has been generated by the GUI designer. Do not modify.
namespace movies
{
	public partial class Window2
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.Label label3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget movies.Window2
			this.Name = "movies.Window2";
			this.Title = global::Mono.Unix.Catalog.GetString("Window2");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child movies.Window2.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Bienvenidos!");
			this.vbox3.Add(this.label3);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label3]));
			w1.Position = 1;
			this.Add(this.vbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
